# Generated by Django 5.0.9 on 2024-11-21 23:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_codigoLibro', models.CharField(max_length=10, unique=True)),
                ('_titulo', models.CharField(max_length=50, unique=True)),
                ('_autor', models.CharField(max_length=50)),
                ('_anioPublicacion', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LibroDigital',
            fields=[
                ('libro_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='BibliotecaAPI.libro')),
                ('_tamanomb', models.PositiveIntegerField()),
                ('_formato', models.CharField(max_length=50)),
            ],
            bases=('BibliotecaAPI.libro',),
        ),
        migrations.CreateModel(
            name='LibroFisico',
            fields=[
                ('libro_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='BibliotecaAPI.libro')),
                ('_numeroPaginas', models.CharField(max_length=20)),
            ],
            bases=('BibliotecaAPI.libro',),
        ),
    ]
