# Generated by Django 5.0.9 on 2024-11-28 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BibliotecaAPI', '0002_remove_libro__aniopublicacion_remove_libro__autor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='librodigital',
            name='tipo_libro',
            field=models.CharField(default='digital', max_length=10),
        ),
        migrations.AddField(
            model_name='librofisico',
            name='tipo_libro',
            field=models.CharField(default='fisica', max_length=10),
        ),
    ]
