# Generated by Django 5.0.9 on 2024-11-28 14:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BibliotecaAPI', '0003_librodigital_tipo_libro_librofisico_tipo_libro'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='anioPublicacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='libro',
            name='autor',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='libro',
            name='codigoLibro',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='libro',
            name='titulo',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='librodigital',
            name='formato',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='librodigital',
            name='tamanomb',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='librofisico',
            name='numeroPaginas',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='librofisico',
            name='tipo_libro',
            field=models.CharField(default='fisico', max_length=10),
        ),
    ]
