# Generated by Django 5.0.9 on 2024-11-28 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BibliotecaAPI', '0004_libro_aniopublicacion_libro_autor_libro_codigolibro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='autor',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='libro',
            name='codigoLibro',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='libro',
            name='titulo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='librodigital',
            name='formato',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='librofisico',
            name='numeroPaginas',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
